version: '2'
services:
  Geoserver:
    container_name: geoserver
    restart: always
    hostname: geoserver
    build: .
    image: kartoza/geoserver:2.9.2
    ports:
      - "8081:8080"
    #links: postgis:postgis
    environment:
      - ORACLE_JDK=true
      - TOMCAT_EXTRAS=false
    volumes:
      - /srv/geoserver/data:/opt/geoserver/data_dir
      - /srv/geoserver/data/tomcat_logs:/usr/local/tomcat/logs

#  Postgis:
#    container_name: postgis
#    restart: always
#    hostname: postgis
#    image: kartoza/postgis:9.5-2.2
#    ports: 

