version: '2'
services:
  Geoserver:
    restart: always
    build: .
    image: kartoza/geoserver:2.9.2
    ports:
      - "8081:8080"
    environment:
      - ORACLE_JDK=true
      - TOMCAT_EXTRAS=false
    volumes:
      - /srv/geoserver/data:/opt/geoserver/data_dir

#DATA_DIR=~/geoserver_data
#if [ ! -d $DATA_DIR ]
#then
#    mkdir -p $DATA_DIR
#fi 

#  Postgis:
#    restart: always
#    image: kartoza/postgis:
#    link: geoserver-postgis:postgis
#    ports:

